# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Flow on the Go
tagline:          'Fast, accurate optical flows on mobile GPUs.'
description:      'Fast, accurate optical flows on mobile GPUs.'
url:
baseurl:          /FlowOnTheGo

author:
  name:           'Ashwin and Richard'

# Custom vars
version:          0.1

github:
  repo:           https://github.com/zhaorz/418project
